### ISSUE TITLE
Not listed on Cocoapods.org?

### ISSUE THREAD

**Issue by ahmetb** [rexstjohn/FourSquareKit#2]
I can't see this on Cocoapods.org search results. http://cocoapods.org/?q=foursquarekit I don't know why. Would you please take a look? I'd love to use this.

**Comment by Ge0rges** [comment]
Please do!

**Comment by lynchspin** [comment]
+1 to the above. Would love to use this.

**Comment by pvtrn** [comment]
+1

**Comment by tkach** [comment]
+1000, please add it to cocoapods master repo.
Now I'm using this way of installing FourSquareKit, but I wish i were able to use it without setting path to git repo.
`pod 'FourSquareKit', :git => 'https://github.com/rexstjohn/FourSquareKit.git', :tag => '0.0.4'`
